new Vue({
    el:"#root",
    data:{
        datas:[
            {
                id:1,
                title:12345,
            },
            {
                id:2,
                title:1234,
            },
            {
                id:3,
                title:123456,
            },
        ],
        state:false,
        title:"",
    },
    methods:{
        aa(){
            this.state=true;
        },
        bb(val){
            this.title = val;
            this.state=false;
        }
    }
})